http:
  listen: "8888"
  destinations:
    /:
      euw1: "http://localhost:8085"
      use1: "http://localhost:8081"

graphql:
  listen: "7777"
  destinations:
    /graph:
      euw1: "http://localhost:7070/graphql"
      use1: "http://localhost:7071/graphql"

grpc:
  listen: "9999"
  destinations:
    /mockserver.v1.MockService/Invoke:
      euw1: "localhost:9095"
      use1: "localhost:9091"
    /mockserver.v1.MockService/BiDirectionalStream:
      euw1: "localhost:9095"
      use1: "localhost:9091"
    /mockserver.v1.MockService/ClientStream:
      euw1: "localhost:9095"
      use1: "localhost:9091"
    /mockserver.v1.MockService/ServerStream:
      euw1: "localhost:9095"
      use1: "localhost:9091"


region_retriever:
  type: "http"
  url: "http://localhost:1234/userinfo"
  method: "GET"
  query_param: "user_id"
  region_resolver:
    type: "map"
    field: "country"
    mapping:
      europe-west1: "euw1"
      eu-west1: "euw1"
      us-east1: "use1"
