http:
  listen: "8888"
  destinations:
    /:
      euw1: "http://example-servers:8085"
      use1: "http://example-servers:8081"

grpc:
  listen: "9999"
  destinations:
      /mockserver.v1.MockService/Invoke:
        euw1: "example-servers:9095"
        use1: "example-servers:9091"
      /mockserver.v1.MockService/BiDirectionalStream:
        euw1: "example-servers:9095"
        use1: "example-servers:9091"
      /mockserver.v1.MockService/ClientStream:
        euw1: "example-servers:9095"
        use1: "example-servers:9091"
      /mockserver.v1.MockService/ServerStream:
        euw1: "example-servers:9095"
        use1: "example-servers:9091"

graphql:
  listen: "7777"
  destinations:
    /graph:
      euw1: "http://example-servers:7070/graphql"
      use1: "http://example-servers:7071/graphql"

region_retriever:
  type: "http"
  url: "http://example-servers:1234/userinfo"
  method: "GET"
  query_param: "user_id"
  region_resolver:
    type: "map"
    field: "country"
    mapping:
      europe-west1: "euw1"
      eu-west1: "euw1"
      us-east1: "use1"
