http:
  listen: "8888"
  destinations:
    - entrypoint: "/"
      mapping:
        euw1: "http://test-server:8085"
        use1: "http://test-server:8081"

grpc:
  listen: "9999"
  destinations:
    - entrypoint: "/mockserver.v1.MockService/Invoke"
      mapping:
        euw1: "test-server:9095"
        use1: "test-server:9091"
    - entrypoint: "/mockserver.v1.MockService/BiDirectionalStream"
      mapping:
        euw1: "test-server:9095"
        use1: "test-server:9091"
    - entrypoint: "/mockserver.v1.MockService/ClientStream"
      mapping:
        euw1: "test-server:9095"
        use1: "test-server:9091"
    - entrypoint: "/mockserver.v1.MockService/ServerStream"
      mapping:
        euw1: "test-server:9095"
        use1: "test-server:9091"


region_retriever:
  type: "http"
  url: "http://test-server:1234/userinfo"
  method: "GET"
  query_param: "user_id"
  region_resolver:
    type: "map"
    field: "country"
    mapping:
      europe-west1: "euw1"
      eu-west1: "euw1"
      us-east1: "use1"
