http:
  listen: "8888"
  destinations:
    - endpoint: "/authorize"
      eu: "https://example.com/"
      us: "https://us.api.example.com:8443"
      asia: "https://asia.api.example.com:8443"
    - endpoint: "/read"
      eu: "https://eu.api.example.com:3333"
      us: "https://us.api.example.com:3333"
      asia: "https://asia.api.example.com:3333"


grpc:
  listen: "9090"
  destinations:
    - endpoint: "/authorize"
      eu: "http://localhost:8081"
      us: "https://us.api.example.com:8443"
    - endpoint: "/read"
      eu: "https://eu.api.example.com:3333"
      us: "https://us.api.example.com:3333"


data_retriever:
  type: "static"
#  endpoint: "http://user-data.example.com/userinfo"
#  method: "GET"
#  query_param: "user_id"
  static: "eu"
  region_resolver:
    type: "map"
    field: "country"
    mapping:
      IT: "eu"
      FR: "eu"
      US: "us"