---
services:
  poly-route:
    networks:
      - poly-route-network
    build:
      context: .
      dockerfile: Dockerfile
    image: canobbioe/poly-route:latest
    ports:
      - "9999:9999"
      - "8888:8888"
    volumes:
      - ./example/docker-config.yaml:/app/config.yaml:ro
    environment:
      - CONFIG_FILE_PATH=/app/config.yaml

  example-servers:
    networks:
      - poly-route-network
    build:
      context: .
      dockerfile: example/server/Dockerfile
    image: canobbioe/poly-route-example-server:latest
    ports:
      - "1234:1234"
      - "8085:8085"
      - "8081:8081"
      - "9095:9095"
      - "9091:9091"

  example-client:
    networks:
      - poly-route-network
    build:
      context: .
      dockerfile: example/client/Dockerfile
    image: canobbioe/poly-route-example-client:latest
    environment:
      - HTTP_HOST=http://poly-route:8888
      - GRPC_HOST=poly-route:9999
    depends_on:
      - example-servers
      - poly-route

networks:
  poly-route-network: