// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: mockserver/v1/mock.proto

package mockserverv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_mockserver_v1_mock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_v1_mock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_mockserver_v1_mock_proto_rawDescGZIP(), []int{0}
}

func (x *ReadRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_mockserver_v1_mock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mockserver_v1_mock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_mockserver_v1_mock_proto_rawDescGZIP(), []int{1}
}

func (x *ReadResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_mockserver_v1_mock_proto protoreflect.FileDescriptor

const file_mockserver_v1_mock_proto_rawDesc = "" +
	"\n" +
	"\x18mockserver/v1/mock.proto\x12\rmockserver.v1\".\n" +
	"\vReadRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"\"\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data2\xba\x02\n" +
	"\vMockService\x12A\n" +
	"\x06Invoke\x12\x1a.mockserver.v1.ReadRequest\x1a\x1b.mockserver.v1.ReadResponse\x12R\n" +
	"\x13BiDirectionalStream\x12\x1a.mockserver.v1.ReadRequest\x1a\x1b.mockserver.v1.ReadResponse(\x010\x01\x12I\n" +
	"\fClientStream\x12\x1a.mockserver.v1.ReadRequest\x1a\x1b.mockserver.v1.ReadResponse(\x01\x12I\n" +
	"\fServerStream\x12\x1a.mockserver.v1.ReadRequest\x1a\x1b.mockserver.v1.ReadResponse0\x01B\x8f\x01\n" +
	"\x11com.mockserver.v1B\tMockProtoP\x01Z\x1amockserver/v1;mockserverv1\xa2\x02\x03MXX\xaa\x02\rMockserver.V1\xca\x02\rMockserver\\V1\xe2\x02\x19Mockserver\\V1\\GPBMetadata\xea\x02\x0eMockserver::V1b\x06proto3"

var (
	file_mockserver_v1_mock_proto_rawDescOnce sync.Once
	file_mockserver_v1_mock_proto_rawDescData []byte
)

func file_mockserver_v1_mock_proto_rawDescGZIP() []byte {
	file_mockserver_v1_mock_proto_rawDescOnce.Do(func() {
		file_mockserver_v1_mock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mockserver_v1_mock_proto_rawDesc), len(file_mockserver_v1_mock_proto_rawDesc)))
	})
	return file_mockserver_v1_mock_proto_rawDescData
}

var file_mockserver_v1_mock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mockserver_v1_mock_proto_goTypes = []any{
	(*ReadRequest)(nil),  // 0: mockserver.v1.ReadRequest
	(*ReadResponse)(nil), // 1: mockserver.v1.ReadResponse
}
var file_mockserver_v1_mock_proto_depIdxs = []int32{
	0, // 0: mockserver.v1.MockService.Invoke:input_type -> mockserver.v1.ReadRequest
	0, // 1: mockserver.v1.MockService.BiDirectionalStream:input_type -> mockserver.v1.ReadRequest
	0, // 2: mockserver.v1.MockService.ClientStream:input_type -> mockserver.v1.ReadRequest
	0, // 3: mockserver.v1.MockService.ServerStream:input_type -> mockserver.v1.ReadRequest
	1, // 4: mockserver.v1.MockService.Invoke:output_type -> mockserver.v1.ReadResponse
	1, // 5: mockserver.v1.MockService.BiDirectionalStream:output_type -> mockserver.v1.ReadResponse
	1, // 6: mockserver.v1.MockService.ClientStream:output_type -> mockserver.v1.ReadResponse
	1, // 7: mockserver.v1.MockService.ServerStream:output_type -> mockserver.v1.ReadResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mockserver_v1_mock_proto_init() }
func file_mockserver_v1_mock_proto_init() {
	if File_mockserver_v1_mock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mockserver_v1_mock_proto_rawDesc), len(file_mockserver_v1_mock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mockserver_v1_mock_proto_goTypes,
		DependencyIndexes: file_mockserver_v1_mock_proto_depIdxs,
		MessageInfos:      file_mockserver_v1_mock_proto_msgTypes,
	}.Build()
	File_mockserver_v1_mock_proto = out.File
	file_mockserver_v1_mock_proto_goTypes = nil
	file_mockserver_v1_mock_proto_depIdxs = nil
}
